version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.19
    - 6.1.20
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: "@ag-grid-enterprise/set-filter"
    versions:
    - 25.1.0
  - dependency-name: "@storybook/theming"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.19
    - 6.1.20
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.13
    - 13.0.2
    - 13.0.3
    - 13.1.1
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.20
    - 6.1.21
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.19.0
  - dependency-name: msw
    versions:
    - 0.27.1
  - dependency-name: "@ag-grid-enterprise/server-side-row-model"
    versions:
    - 25.1.0
  - dependency-name: "@ag-grid-enterprise/row-grouping"
    versions:
    - 25.1.0
  - dependency-name: "@ag-grid-community/csv-export"
    versions:
    - 25.1.0
  - dependency-name: "@ag-grid-enterprise/status-bar"
    versions:
    - 25.1.0
  - dependency-name: "@ag-grid-enterprise/excel-export"
    versions:
    - 25.1.0
  - dependency-name: husky
    versions:
    - 5.1.1
    - 5.1.2
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.19
    - 6.1.20
  - dependency-name: np
    versions:
    - 7.3.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.15
    - 6.1.16
