name: NPM publish

on:
  push:
    branches:    
      # Push events on main branch
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: Build
      run: npm run build
    - name: Publish
      id: publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}

    - if: steps.publish.outputs.type != 'none'
      name: Create release
      uses: release-drafter/release-drafter@v5.12.1
      with: 
        publish: true
        version: ${{ steps.publish.outputs.version }}
        tag: ${{ steps.publish.outputs.version }}

      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

